### ISSUE TITLE
При добавлении карточки отображается ошибка

### ISSUE THREAD

**Issue by koras** [blanshec/yp_mesto-server#3]
{
    "message": "Запрашиваемый ресурс не найден"
}

**Comment by koras** [comment]
https://i.imgur.com/zXKfiNB.png

**Comment by blanshec** [comment]
Не могу воссоздать ошибку со своей стороны, как данную проблему (добавление карточки), так и проблему с добавлением пользователя. Отталкиваясь от пришедшего ответа - мое единственное предположение на данный момент, что была клонирована мастер, а не девелоп ветка. Прошу подтвердить или опровергнуть
Спасибо
[https://imgur.com/a/KCYfuln](url)

**Comment by koras** [comment]
В брифе указано что у вас должно быть 3 ветки и должен быть сделан pull request.
У вас ни того не другого, соответственно я проверяю ту ветку которую посчитаю сам правильной, master. 
Согласно внутренним правилам я должен был не принять вашу работу пока не будет pull request со всеми изменениями, для того чтобы я мог прокомментировать весь код. Сейчас я не могу его прокомментировать и пишу сюда.
Работа принимается.
